(defcaixa
  :name
  "lava-kubernetes"
  :kind
  :Biblioteca
  :ecosystem
  :rust-single-crate
  :package
  {:name "lava-kubernetes"
   :version "0.1.0"
   :description "Tatara-lisp typed surface for kubernetes resources. Auto-generated by lava-forge from the kubernetes TF provider schema. Pangea-kubernetes analog."
   :license "MIT"
   :repository "https://github.com/pleme-io/lava-kubernetes"}
  :ci-config
  {:bump {:default-type "patch"}
   :publish {:no-verify true}}
  :workflows
  [:auto-release :pre-merge-gate :security-gate])
