# nix/modules/nixos.nix — auto-generated from lava-kubernetes.caixa.lisp
# description: "Tatara-lisp typed surface for kubernetes resources. Auto-generated by lava-forge from the kubernetes TF provider schema. Pangea-kubernetes analog."
{ config, lib, pkgs, ... }:
let
  cfg = config.services.lava-kubernetes;
in {
  options.services.lava-kubernetes = {
    enable = lib.mkEnableOption "lava-kubernetes";
    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.lava-kubernetes or null;
    };
  };
  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ cfg.package ];
  };
}
