//! pleme-io typed wrapper — auto-generated by caixa-forge.
//!
//! Replace this stub with the actual library implementation.
//! The smoke test below ensures `cargo test` is green by default.

#[cfg(test)]
mod tests {
    #[test]
    fn smoke() {
        assert_eq!(2 + 2, 4);
    }
}
